catalog=[
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},
{
    title:"Companies act, 1994 (Authentic English Text)",
    call_no:"346.067 COM 1995 ENG",
    authors:"Ministry of Commerce,Bd",
    category:" Law  [ Browse Items ]",
    publication_year:1995,
    publisher:"",
    pages:292,
    subject:"LAW",
    Tags:"",
    Abstract:"",
    Description:"",
    biblio_Notes:"",
    number_of_copies:2
},


]